services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile   
    container_name: backend-prod
    network_mode: "bridge"      
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production    
    env_file:
      - .env                    